#!/bin/bash
#

# Script to download, Silent Install and then clean up once installed 

#Make temp folder for downloads.
mkdir "/tmp/browsers/";
cd "/tmp/browsers/";

#Download Chrome

curl -L -o /tmp/browsers/chrome.dmg "https://dl.google.com/chrome/mac/universal/stable/GGRO/googlechrome.dmg";

#Mount DMG

hdiutil attach /tmp/browsers/chrome.dmg;

#Copy App to Applications

sudo cp -R "/Volumes/Google Chrome/Google Chrome.app" /Applications;

#Unmount DMG

hdiutil detach "/Volumes/Google Chrome";

#Remove Temp Files (Temp Removed)
sudo rm -rf "/tmp/browsers/";