#!/bin/bash
#

if 
	[ -f /Library/Logs/sentinelone-install-log.txt ]
then
	exit 0
else
# Installation process

#Download SentinelOne
cd /tmp
curl -L -o /tmp/Sentinel-23-2-2-6951.pkg curl -L "https://drive.usercontent.google.com/download?id=1S6hd2SvU3SZLT9c4lOxQvrf32kBfSWRX&confirm=xxx" -o Sentinel-23-2-2-6951.pkg

sudo echo > /tmp/com.sentinelone.registration-token "eyJ1cmwiOiAiaHR0cHM6Ly9ldWNlMS0xMDQuc2VudGluZWxvbmUubmV0IiwgInNpdGVfa2V5IjogImFiYzhmNDA5YzljNDczYTkifQ=="
sudo /usr/sbin/installer -pkg /tmp/Sentinel-23-2-2-6951.pkg -target /
sleep 3 
sudo /usr/local/bin/sentinelctl set registration-token -- "eyJ1cmwiOiAiaHR0cHM6Ly9ldWNlMS0xMDQuc2VudGluZWxvbmUubmV0IiwgInNpdGVfa2V5IjogImFiYzhmNDA5YzljNDczYTkifQ=="
fi

sudo echo > /Library/Logs/sentinelone-install-log.txt 'Sentinelone Agent has been installed successful'

######### STEP 5
######### SLACK INSTALLATION
#Make temp folder for downloads.
mkdir "/tmp/slack/";
cd "/tmp/slack/";

#Download Slack.
curl -L -o /tmp/slack/slack.dmg "https://slack.com/ssb/download-osx";

#Mount DMG
hdiutil attach /tmp/slack/slack.dmg;

#Copy App to Applications
sudo cp -R "/Volumes/Slack/Slack.app" /Applications;

#Unmount DMG
hdiutil detach /Volumes/Slack;

#tidy up
sudo rm -rf "/tmp/slack";

Sleep 5

######### STEP 6
######### OFFICE INSTALLATION
#Make temp folder for downloads.
mkdir "/tmp/office/";
cd "/tmp/office/";

#Download Word, PowerPoint and Excel into temp folder.
curl -L -o /tmp/office/word.pkg "https://go.microsoft.com/fwlink/?linkid=525134";
curl -L -o /tmp/office/powerpoint.pkg "https://go.microsoft.com/fwlink/?linkid=525136";
curl -L -o /tmp/office/excel.pkg "https://go.microsoft.com/fwlink/?linkid=525135";

#Silent Install each application.
sudo -S installer -allowUntrusted -pkg "/tmp/office/word.pkg" -target /;
sudo -S installer -allowUntrusted -pkg "/tmp/office/powerpoint.pkg" -target /;
sudo -S installer -allowUntrusted -pkg "/tmp/office/excel.pkg" -target /;

#Remove Temp Files
sudo rm -rf "/tmp/office/";

# Script to download, Silent Install and then clean up once installed 

#Make temp folder for downloads.
mkdir "/tmp/browsers/";
cd "/tmp/browsers/";

Sleep 5

######### STEP 6
######################### Chrome INSTALLATION

curl -L -o /tmp/browsers/chrome.dmg "https://dl.google.com/chrome/mac/universal/stable/GGRO/googlechrome.dmg";

#Mount DMG

hdiutil attach /tmp/browsers/chrome.dmg;

#Copy App to Applications

sudo cp -R "/Volumes/Google Chrome/Google Chrome.app" /Applications;

#Unmount DMG

hdiutil detach "/Volumes/Google Chrome";

#Remove Temp Files (Temp Removed)
sudo rm -rf "/tmp/browsers/";